wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1660397976.909987
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.7.13
      5: 0.13.1
      8:
      - 3
      - 5
